name: Check git apply

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: bromite
          fetch-depth: 1
          
      - name: Prepare container
        run: |
          sudo apt update
          sudo apt install -y wget unzip sqlite3
          wget https://github.com/uazo/superpatch/releases/latest/download/SuperPatchUtils.tar.gz
          tar xfz SuperPatchUtils.tar.gz
